name: dartz
version: 0.2.1
homepage: https://github.com/spebbe/dartz
description: Functional Programming in Dart.
author: Björn Sperber <spebbe@gmail.com>

environment:
  sdk: '>=1.16.0 <2.0.0'

dev_dependencies:
  test: "^0.12.4+5"
  propcheck: "^0.5.1"
